const artList = [
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example1",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example2",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        title: "example3",
        desc: "",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example4",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example5",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        title: "example6",
        desc: "",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example7",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example8",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        title: "example9",
        desc: "",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example10",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example11",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        title: "example12",
        desc: "",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example13",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example14",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        title: "example15",
        desc: "",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example16",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        title: "example17",
        desc: "",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        title: "example18",
        desc: "",
        cat: "",
    },
];