const artList = [
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example1",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example2",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        alt: "example3",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example4",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example5",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        alt: "example6",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example7",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example8",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        alt: "example9",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example10",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example11",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        alt: "example12",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example13",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example14",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        alt: "example15",
        cat: "",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example16",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree2.png",
        url: "../assets/mid_1080p/filigree2.png",
        alt: "example17",
        cat: "sketchbook",
    },
    {
        thumb: "../assets/mid_1080p/filigree1.png",
        url: "../assets/mid_1080p/filigree1.png",
        alt: "example18",
        cat: "",
    },
];